name: Project Checks

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - package-lock-only

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build web app
        run: npm run build